"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import plugins
from plugins.model.mek_rotation_info_model import MEKRotationInfoModel
from plugins.model.mek_rotation_process_state_types import MEKRotationProcessStateTypes
globals()['MEKRotationInfoModel'] = MEKRotationInfoModel
globals()['MEKRotationProcessStateTypes'] = MEKRotationProcessStateTypes
from plugins.model.mek_rotation_info_response_view_model import MEKRotationInfoResponseViewModel


class TestMEKRotationInfoResponseViewModel(unittest.TestCase):
    """MEKRotationInfoResponseViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMEKRotationInfoResponseViewModel(self):
        """Test MEKRotationInfoResponseViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MEKRotationInfoResponseViewModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
