"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import plugins
from plugins.model.recurring_schedule_entity_model import RecurringScheduleEntityModel
from plugins.model.recurring_schedule_type import RecurringScheduleType
from plugins.model.recurring_schedule_value_model import RecurringScheduleValueModel
globals()['RecurringScheduleEntityModel'] = RecurringScheduleEntityModel
globals()['RecurringScheduleType'] = RecurringScheduleType
globals()['RecurringScheduleValueModel'] = RecurringScheduleValueModel
from plugins.model.recurring_schedule_create_model import RecurringScheduleCreateModel


class TestRecurringScheduleCreateModel(unittest.TestCase):
    """RecurringScheduleCreateModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecurringScheduleCreateModel(self):
        """Test RecurringScheduleCreateModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecurringScheduleCreateModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
