"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import plugins
from plugins.model.update_field_value_of_boolean import UpdateFieldValueOfBoolean
from plugins.model.update_field_value_of_event_pipeline_filter_map_update_model_array import UpdateFieldValueOfEventPipelineFilterMapUpdateModelArray
from plugins.model.update_field_value_of_event_pipeline_task_map_update_model_array import UpdateFieldValueOfEventPipelineTaskMapUpdateModelArray
from plugins.model.update_field_value_of_event_pipeline_trigger_update_model_array import UpdateFieldValueOfEventPipelineTriggerUpdateModelArray
from plugins.model.update_field_value_of_string import UpdateFieldValueOfString
globals()['UpdateFieldValueOfBoolean'] = UpdateFieldValueOfBoolean
globals()['UpdateFieldValueOfEventPipelineFilterMapUpdateModelArray'] = UpdateFieldValueOfEventPipelineFilterMapUpdateModelArray
globals()['UpdateFieldValueOfEventPipelineTaskMapUpdateModelArray'] = UpdateFieldValueOfEventPipelineTaskMapUpdateModelArray
globals()['UpdateFieldValueOfEventPipelineTriggerUpdateModelArray'] = UpdateFieldValueOfEventPipelineTriggerUpdateModelArray
globals()['UpdateFieldValueOfString'] = UpdateFieldValueOfString
from plugins.model.event_pipeline_update_model import EventPipelineUpdateModel


class TestEventPipelineUpdateModel(unittest.TestCase):
    """EventPipelineUpdateModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventPipelineUpdateModel(self):
        """Test EventPipelineUpdateModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EventPipelineUpdateModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
