"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import plugins
from plugins.model.field_data_type import FieldDataType
globals()['FieldDataType'] = FieldDataType
from plugins.model.secret_template_field_create_model import SecretTemplateFieldCreateModel


class TestSecretTemplateFieldCreateModel(unittest.TestCase):
    """SecretTemplateFieldCreateModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecretTemplateFieldCreateModel(self):
        """Test SecretTemplateFieldCreateModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecretTemplateFieldCreateModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
