"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import plugins
from plugins.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_service_add_user_owner(self):
        """Test case for users_service_add_user_owner

        Add User Owner  # noqa: E501
        """
        pass

    def test_users_service_add_user_to_groups(self):
        """Test case for users_service_add_user_to_groups

        Add groups to existing user  # noqa: E501
        """
        pass

    def test_users_service_change_password(self):
        """Test case for users_service_change_password

        Change User Password  # noqa: E501
        """
        pass

    def test_users_service_create_user(self):
        """Test case for users_service_create_user

        Create User  # noqa: E501
        """
        pass

    def test_users_service_create_user_public_ssh_key(self):
        """Test case for users_service_create_user_public_ssh_key

        Create a User Ssh Key  # noqa: E501
        """
        pass

    def test_users_service_create_user_roles(self):
        """Test case for users_service_create_user_roles

        Add roles to existing user  # noqa: E501
        """
        pass

    def test_users_service_deactivate_user_public_ssh_key(self):
        """Test case for users_service_deactivate_user_public_ssh_key

        Deactivate SSH Key  # noqa: E501
        """
        pass

    def test_users_service_delete(self):
        """Test case for users_service_delete

        Delete User  # noqa: E501
        """
        pass

    def test_users_service_delete_user_owner(self):
        """Test case for users_service_delete_user_owner

        Remove User Owner  # noqa: E501
        """
        pass

    def test_users_service_delete_user_roles(self):
        """Test case for users_service_delete_user_roles

        Remove roles from existing user  # noqa: E501
        """
        pass

    def test_users_service_get(self):
        """Test case for users_service_get

        Get User  # noqa: E501
        """
        pass

    def test_users_service_get_current_user(self):
        """Test case for users_service_get_current_user

        Current User  # noqa: E501
        """
        pass

    def test_users_service_get_current_user_sessions(self):
        """Test case for users_service_get_current_user_sessions

        User Sessions  # noqa: E501
        """
        pass

    def test_users_service_get_domains(self):
        """Test case for users_service_get_domains

        Get Domains  # noqa: E501
        """
        pass

    def test_users_service_get_preference(self):
        """Test case for users_service_get_preference

        Get Preference  # noqa: E501
        """
        pass

    def test_users_service_get_roles(self):
        """Test case for users_service_get_roles

        Gets roles for user  # noqa: E501
        """
        pass

    def test_users_service_get_site_audits(self):
        """Test case for users_service_get_site_audits

        User Audits  # noqa: E501
        """
        pass

    def test_users_service_get_user_action_audits(self):
        """Test case for users_service_get_user_action_audits

        User Audits by Action  # noqa: E501
        """
        pass

    def test_users_service_get_user_groups(self):
        """Test case for users_service_get_user_groups

        Get User Groups  # noqa: E501
        """
        pass

    def test_users_service_get_user_owner(self):
        """Test case for users_service_get_user_owner

        Get User Owner  # noqa: E501
        """
        pass

    def test_users_service_get_user_public_ssh_keys(self):
        """Test case for users_service_get_user_public_ssh_keys

        Get User Public Ssh Keys  # noqa: E501
        """
        pass

    def test_users_service_get_user_roles(self):
        """Test case for users_service_get_user_roles

        Get User Roles  # noqa: E501
        """
        pass

    def test_users_service_get_user_teams(self):
        """Test case for users_service_get_user_teams

        User Teams  # noqa: E501
        """
        pass

    def test_users_service_lock_out(self):
        """Test case for users_service_lock_out

        Lock Out  # noqa: E501
        """
        pass

    def test_users_service_lookup(self):
        """Test case for users_service_lookup

        Lookup Users  # noqa: E501
        """
        pass

    def test_users_service_patch_user(self):
        """Test case for users_service_patch_user

        Update included properties for user by Id  # noqa: E501
        """
        pass

    def test_users_service_patch_user_owners(self):
        """Test case for users_service_patch_user_owners

        Add and remove the owners on the user  # noqa: E501
        """
        pass

    def test_users_service_remove_user_groups(self):
        """Test case for users_service_remove_user_groups

        Remove groups from existing user  # noqa: E501
        """
        pass

    def test_users_service_reset_two_factor(self):
        """Test case for users_service_reset_two_factor

        Reset 2FA  # noqa: E501
        """
        pass

    def test_users_service_reset_user_password(self):
        """Test case for users_service_reset_user_password

        Reset a user password as an admin  # noqa: E501
        """
        pass

    def test_users_service_search_user_owners(self):
        """Test case for users_service_search_user_owners

        Get User Owners  # noqa: E501
        """
        pass

    def test_users_service_search_users(self):
        """Test case for users_service_search_users

        Search Users  # noqa: E501
        """
        pass

    def test_users_service_set_user_double_lock_password(self):
        """Test case for users_service_set_user_double_lock_password

        Update Users Doublelock Password  # noqa: E501
        """
        pass

    def test_users_service_stub(self):
        """Test case for users_service_stub

        Get User Stub  # noqa: E501
        """
        pass

    def test_users_service_terminate_current_user_sessions(self):
        """Test case for users_service_terminate_current_user_sessions

        Terminate Current User Sessions  # noqa: E501
        """
        pass

    def test_users_service_update_preference(self):
        """Test case for users_service_update_preference

        Update Preference  # noqa: E501
        """
        pass

    def test_users_service_update_user(self):
        """Test case for users_service_update_user

        Update User  # noqa: E501
        """
        pass

    def test_users_service_update_user_groups(self):
        """Test case for users_service_update_user_groups

        Update all groups on user  # noqa: E501
        """
        pass

    def test_users_service_update_user_roles(self):
        """Test case for users_service_update_user_roles

        Update all roles on user  # noqa: E501
        """
        pass

    def test_users_service_user_personal_info_delete_command(self):
        """Test case for users_service_user_personal_info_delete_command

        Delete a user's personally identifiable info  # noqa: E501
        """
        pass

    def test_users_service_verify_password(self):
        """Test case for users_service_verify_password

        Verify the Current User Password  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
