"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import plugins
from plugins.api.ssh_command_api import SshCommandApi  # noqa: E501


class TestSshCommandApi(unittest.TestCase):
    """SshCommandApi unit test stubs"""

    def setUp(self):
        self.api = SshCommandApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ssh_command_service_create_ssh_command(self):
        """Test case for ssh_command_service_create_ssh_command

        Add an SSH Command  # noqa: E501
        """
        pass

    def test_ssh_command_service_get_ssh_command(self):
        """Test case for ssh_command_service_get_ssh_command

        Get an SSH Command  # noqa: E501
        """
        pass

    def test_ssh_command_service_get_ssh_command_stub(self):
        """Test case for ssh_command_service_get_ssh_command_stub

        Stub an empty SSH Command  # noqa: E501
        """
        pass

    def test_ssh_command_service_get_ssh_commands(self):
        """Test case for ssh_command_service_get_ssh_commands

        Get a list of SSH Commands  # noqa: E501
        """
        pass

    def test_ssh_command_service_update_ssh_command(self):
        """Test case for ssh_command_service_update_ssh_command

        Update an SSH Command  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
