"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import plugins
from plugins.model.dev_ops_secret_vault_sync_update_model import DevOpsSecretVaultSyncUpdateModel
globals()['DevOpsSecretVaultSyncUpdateModel'] = DevOpsSecretVaultSyncUpdateModel
from plugins.model.dev_ops_secrets_vault_create_sync_args import DevOpsSecretsVaultCreateSyncArgs


class TestDevOpsSecretsVaultCreateSyncArgs(unittest.TestCase):
    """DevOpsSecretsVaultCreateSyncArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDevOpsSecretsVaultCreateSyncArgs(self):
        """Test DevOpsSecretsVaultCreateSyncArgs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DevOpsSecretsVaultCreateSyncArgs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
