"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import plugins
from plugins.api.event_pipeline_settings_api import EventPipelineSettingsApi  # noqa: E501


class TestEventPipelineSettingsApi(unittest.TestCase):
    """EventPipelineSettingsApi unit test stubs"""

    def setUp(self):
        self.api = EventPipelineSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_event_pipeline_settings_service_get_event_pipeline_filter_settings(self):
        """Test case for event_pipeline_settings_service_get_event_pipeline_filter_settings

        Get Event Pipeline Filter Settings  # noqa: E501
        """
        pass

    def test_event_pipeline_settings_service_get_event_pipeline_task_settings(self):
        """Test case for event_pipeline_settings_service_get_event_pipeline_task_settings

        Get Event Pipeline Task Settings  # noqa: E501
        """
        pass

    def test_event_pipeline_settings_service_get_event_pipeline_tasks(self):
        """Test case for event_pipeline_settings_service_get_event_pipeline_tasks

        Get Event Pipeline Tasks  # noqa: E501
        """
        pass

    def test_event_pipeline_settings_service_get_pipeline_filter_options(self):
        """Test case for event_pipeline_settings_service_get_pipeline_filter_options

        Get Pipeline Filter Options  # noqa: E501
        """
        pass

    def test_event_pipeline_settings_service_get_pipeline_task_options(self):
        """Test case for event_pipeline_settings_service_get_pipeline_task_options

        Get Pipeline Task Options  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
